### ISSUE TITLE
Error signing BIP-322 simple with legacy address

### ISSUE THREAD

**Issue by kevzzsk** [unisat-wallet/extension#118]
Signing with `await window.unisat.signMessage("message", "bip322-simple")` on a legacy address produces error stack 
```json
{
    "code": -32603,
    "message": "Input #0 has witnessUtxo but non-segwit script: 76a9148a9c5ece63e8bb16c93aeaec8d1462b34137132588ac",
    "data": {
        "originalError": {
            "message": "Input #0 has witnessUtxo but non-segwit script: 76a9148a9c5ece63e8bb16c93aeaec8d1462b34137132588ac",
            "stack": "Error: Input #0 has witnessUtxo but non-segwit script: 76a9148a9c5ece63e8bb16c93aeaec8d1462b34137132588ac\n    at X (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:410751)\n    at G (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:409900)\n    at v.value (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:400524)\n    at v.value (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:400037)\n    at chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:206169\n    at Array.forEach (<anonymous>)\n    at chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:205589\n    at f (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1328172)\n    at c.value (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1327930)\n    at Generator.next (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1328527)"
        }
    }
}
```

signing with other formats, works fine

**Comment by cloud6605** [comment]
Got it, thanks for your feedback. We'll fix it in the next version.
